---
code_red_breach_challenge_gitea_customize_gitea_namespace: gitea
code_red_breach_challenge_gitea_customize_gitea_admin_user: gitea
code_red_breach_challenge_gitea_customize_gitea_admin_password: AVo2zmNf34KptdHe #notsecret
code_red_breach_challenge_gitea_customize_gitea_public_repos:
- name: customers-app
  url: https://github.com/rhpds/code-red-breach-challenge-customers-app.git
  per_user: false
  private: false
- name: customers-gitops
  url: https://github.com/rhpds/code-red-breach-challenge-customers-gitops.git
  per_user: true
  private: true
- name: env-gitops
  url: https://github.com/rhpds/code-red-breach-challenge-env-gitops.git
  per_user: true
  private: true
- name: pipeline-gitops
  url: https://github.com/rhpds/code-red-breach-challenge-pipeline-gitops.git
  per_user: true
  private: true
- name: leaderboard-gitops
  url: https://github.com/rhpds/code-red-breach-challenge-leaderboard-gitops.git
  per_user: false
  private: true
code_red_breach_challenge_gitea_customize_gitea_num_users: "{{ num_users | default(3) }}"
code_red_breach_challenge_gitea_customize_gitea_user_name_base: user
code_red_breach_challenge_gitea_customize_gitea_user_password: MTg5OTIy #notsecret
code_red_breach_challenge_gitea_customize_student_name: "{{ student_name | default('lab-user') }}"
code_red_breach_challenge_gitea_customize_lab_challenge_password: Z9YagGvef1716QFZdVff9MF9iOpd5RCS4Ct3AwOzWsp3sesxkYIYl0QtEPv2Zhzd #notsecret
code_red_breach_challenge_argo_customize_pat_token_part1: "github_"
code_red_breach_challenge_argo_customize_pat_token_part2: "pat_11"
code_red_breach_challenge_argo_customize_pat_token_part3: "ACG6BGI07nJ3ve51tGkM_lyPhA15Rginj71Y28iyoYYn9vePzUv7oTwm5CZGjUWQZIO7HLDHqxXzQTzo"
